name: Go Build

#on: [push]
on:
  push:
    branches:
      - master
  tags:
    - 'v*'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.18
    - name: Build client
      run: GO111MODULE=off GOPATH=$PWD go build -o ssh-keep-c client.go
    - name: Build server
      run: GO111MODULE=off GOPATH=$PWD go build -o ssh-keep-s server.go
